"""Initial migration

Revision ID: 6a47c89eeeac
Revises: 
Create Date: 2026-06-14 12:42:04.071571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a47c89eeeac'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batches',
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('batch_id')
    )
    op.create_table('departments',
    sa.Column('dept_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('dept_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('subjects',
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('subject_id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('teachers',
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('teacher_id')
    )
    op.create_table('timeslots',
    sa.Column('timeslot_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.String(length=20), nullable=False),
    sa.Column('start_time', sa.String(length=10), nullable=False),
    sa.Column('end_time', sa.String(length=10), nullable=False),
    sa.Column('slot_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('timeslot_id'),
    sa.UniqueConstraint('slot_order')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('teacher_assignments',
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('teacher_id', sa.Integer(), nullable=False),
    sa.Column('dept_id', sa.Integer(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.batch_id'], ),
    sa.ForeignKeyConstraint(['dept_id'], ['departments.dept_id'], ),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.subject_id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.teacher_id'], ),
    sa.PrimaryKeyConstraint('assignment_id')
    )
    op.create_table('timetables',
    sa.Column('timetable_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('dept_id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.batch_id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['dept_id'], ['departments.dept_id'], ),
    sa.PrimaryKeyConstraint('timetable_id')
    )
    op.create_table('timetableentries',
    sa.Column('tt_entry_id', sa.Integer(), nullable=False),
    sa.Column('ta_id', sa.Integer(), nullable=False),
    sa.Column('timeslot_id', sa.Integer(), nullable=False),
    sa.Column('timetable_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ta_id'], ['teacher_assignments.assignment_id'], ),
    sa.ForeignKeyConstraint(['timeslot_id'], ['timeslots.timeslot_id'], ),
    sa.ForeignKeyConstraint(['timetable_id'], ['timetables.timetable_id'], ),
    sa.PrimaryKeyConstraint('tt_entry_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timetableentries')
    op.drop_table('timetables')
    op.drop_table('teacher_assignments')
    op.drop_table('users')
    op.drop_table('timeslots')
    op.drop_table('teachers')
    op.drop_table('subjects')
    op.drop_table('departments')
    op.drop_table('batches')
    # ### end Alembic commands ###
